### ISSUE TITLE
Feature Request - Saved Recent IP's to Config for Easy Reuse

### ISSUE THREAD

**Issue by ferrouslights** [Hifumi1337/droid#2]
Adding any new IP's to a config file and showing from a dropdown for easy reselection would be convenient for users that need to switch between devices on the fly.

**Comment by Hifumi1337** [comment]
This feature was included in this release: [v1.3.16](https://github.com/Hifumi1337/droid/releases/tag/v1.3.16) (which just came out!)

For now, you can add IP addresses manually and then just type in the key (key:value) of the specific IP address you'd like to use. May include a dropdown in future releases within the actual GUI once the remaining CLI commands are complete. Will keep this issue open until the dropdown is implemented (gonna try and include it in the v1.4/5.x  release).

You can see the functionality here: https://github.com/Hifumi1337/droid/blob/40399388137339f4654233adca5d961fe1a54f9e/utils/view.py#L118-L135
